queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check docker [x86_64-linux]
      - check-success=check podman [x86_64-linux]
      - check-success=default devShell [x86_64-linux]
      - check-success=default package [x86_64-linux]
      - check-success=package cntr [x86_64-linux]
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      queue: {}
