[package]
name = "cntr"
edition = "2024"
rust-version = "1.85"
description = "A container debugging tool based on Linux mount API"
version = "2.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
categories = ["development-tools::debugging", "os::unix-apis"]
repository = "https://github.com/Mic92/cntr"
license = "MIT"

[dependencies]
log = "0.4.30"
container-pid = "2.0"
thiserror = "2"
rustix = { version = "1.1.4", features = [
  "event",
  "fs",
  "mount",
  "net",
  "pipe",
  "process",
  "pty",
  "stdio",
  "termios",
  "thread",
] }
libc = "0.2.189"

[[bin]]
name = "cntr"
path = "src/bin/main.rs"
